# Generated by Django 5.2.2 on 2025-07-04 17:50
import logging

from django.db import migrations, connection


def remove_tables(apps, schema_editor):
    print('dropping client tables')
    with connection.cursor() as cursor:
        cursor.execute('DROP TABLE IF EXISTS client_clientwebhook CASCADE')
        cursor.execute('DROP TABLE IF EXISTS client_clientenvironment CASCADE')
        cursor.execute('DROP TABLE IF EXISTS client_clientcontact CASCADE')
        cursor.execute('DROP TABLE IF EXISTS client_client CASCADE')
        print('client tables dropped')


class Migration(migrations.Migration):
    dependencies = []

    operations = [
        migrations.RunPython(remove_tables),
    ]
