# Generated by Django 5.2.2 on 2025-07-16 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_account_django_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='django_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='django_pk',
            new_name='uuid',
        ),
        migrations.RemoveField(
            model_name='account',
            name='description',
        ),
        migrations.RemoveField(
            model_name='account',
            name='quota',
        ),
        migrations.RemoveField(
            model_name='account',
            name='secret',
        ),
        migrations.RemoveField(
            model_name='account',
            name='type',
        ),
        migrations.DeleteModel(
            name='GroupMember',
        ),
    ]
