# Generated by Django 5.2.2 on 2025-07-16 20:34

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mail', '0003_rename_django_user_account_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='django_pk',
            new_name='uuid',
        ),
        migrations.AddField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='email',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='email',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
