# Generated by Django 5.2.2 on 2025-07-16 20:38

import django.db.models.deletion
import thunderbird_accounts.mail.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0004_remove_email_django_pk_account_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='email',
            name='mail_email_name_9708d8_idx',
        ),
        migrations.RemoveField(
            model_name='email',
            name='name',
        ),
        migrations.AddField(
            model_name='email',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mail.account'),
        ),
        migrations.AlterField(
            model_name='email',
            name='address',
            field=thunderbird_accounts.mail.models.SmallTextField(help_text='Full email address.', unique=True),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['address'], name='mail_email_address_538081_idx'),
        ),
    ]
