# Generated by Django 5.2.4 on 2025-10-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0005_remove_email_mail_email_name_9708d8_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='stalwart_created_at',
            field=models.DateTimeField(help_text='Date that this object was created by this system in Stalwart.', null=True, editable=False),
        ),
        migrations.AddField(
            model_name='account',
            name='stalwart_id',
            field=models.CharField(help_text="The unique ID in Stalwart. (Note: That this isn't useful for anything besides verifying that it exists in Stalwart.", null=True, editable=False),
        ),
        migrations.AddField(
            model_name='account',
            name='stalwart_updated_at',
            field=models.DateTimeField(help_text='Date that this object was last updated by this system in Stalwart.', null=True, editable=False),
        ),
    ]
