# Generated by Django 5.2.4 on 2025-10-24 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0006_account_stalwart_created_at_account_stalwart_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='quota',
            field=models.BigIntegerField(help_text='Amount of mail storage this account has access to (in bytes).', null=True),
        ),
    ]
