# Generated by Django 5.2.4 on 2025-10-27 21:52

import django.db.models.deletion
import thunderbird_accounts.mail.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0006_account_stalwart_created_at_account_stalwart_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stalwart_id', models.CharField(editable=False, help_text="The unique ID in Stalwart. (Note: That this isn't useful for anything besides verifying that it exists in Stalwart.", null=True)),
                ('stalwart_created_at', models.DateTimeField(editable=False, help_text='Date that this object was created by this system in Stalwart.', null=True)),
                ('stalwart_updated_at', models.DateTimeField(editable=False, help_text='Date that this object was last updated by this system in Stalwart.', null=True)),
                ('name', thunderbird_accounts.mail.models.SmallTextField(help_text='The domain name (e.g., example.com)', unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('failed', 'Verification Failed')], default='pending', help_text='Current verification status of the domain', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, help_text='Date and time when the domain was verified', null=True)),
                ('last_verification_attempt', models.DateTimeField(blank=True, help_text='Date and time of the last verification attempt', null=True)),
                ('user', models.ForeignKey(help_text='The user who owns this domain', on_delete=django.db.models.deletion.CASCADE, related_name='domains', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['stalwart_id'], name='mail_domain_stalwar_928747_idx'), models.Index(fields=['stalwart_created_at'], name='mail_domain_stalwar_a09a3c_idx'), models.Index(fields=['stalwart_updated_at'], name='mail_domain_stalwar_a96545_idx')],
            },
        ),
    ]
