# Generated by Django 5.2.4 on 2025-10-29 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0007_account_quota'),
        ('mail', '0007_domain'),
    ]

    operations = [
    ]
