# Generated by Django 5.2.9 on 2025-12-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0008_merge_0007_account_quota_0007_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='verified_archive_folder',
            field=models.BooleanField(default=False, help_text='On login we check if they have an archive folder. If this is true that check will be skipped.'),
        ),
    ]
