authentication.fallback-admin.secret = "%{env:ADMIN_SECRET}%"
authentication.fallback-admin.user = "admin"
directory.internal.store = "rocksdb"
directory.internal.type = "internal"
directory.kc.auth.method = "basic"
directory.kc.auth.secret = "Kfo2GJdGs2ItfiTgGPahXpT3yTKUlYOj"
directory.kc.auth.username = "stalwart"
directory.kc.bind.auth.method = "default"
directory.kc.cache.size = 1048576
directory.kc.cache.ttl.negative = "10m"
directory.kc.cache.ttl.positive = "1h"
directory.kc.endpoint.method = "introspect"
directory.kc.endpoint.url = "http://keycloak:8999/realms/tbpro/protocol/openid-connect/token/introspect"
directory.kc.fields.email = "username"
directory.kc.timeout = "15s"
directory.kc.type = "oidc"
http.rate-limit.anonymous = "10000/1m"
server.hostname = "stalwart_legacy"
server.listener.imap.bind.0000 = "[::]:143"
server.listener.imap.protocol = "imap"
server.listener.imaptls.bind.0000 = "[::]:993"
server.listener.imaptls.protocol = "imap"
server.listener.imaptls.tls.implicit = true
server.listener.jmap.bind.0000 = "[::]:8081"
server.listener.jmap.protocol = "http"
server.listener.management.bind.0000 = "[::]:8080"
server.listener.management.protocol = "http"
server.listener.smtp.bind.0000 = "[::]:25"
server.listener.smtp.protocol = "smtp"
server.listener.submissions.bind.0000 = "[::]:465"
server.listener.submissions.protocol = "smtp"
server.listener.submissions.tls.implicit = true
server.max-connections = 8192
server.socket.backlog = 1024
server.socket.nodelay = true
server.socket.reuse-addr = true
server.socket.reuse-port = true
storage.blob = "rocksdb"
storage.data = "rocksdb"
storage.directory = "kc"
storage.fts = "rocksdb"
storage.lookup = "rocksdb"
store.rocksdb.compression = "lz4"
store.rocksdb.path = "%{env:MAIL_STALWART_PATH}%/data"
store.rocksdb.type = "rocksdb"
tracer.stdout.ansi = false
tracer.stdout.enable = true
tracer.stdout.level = "info"
tracer.stdout.type = "stdout"
