# Generated by Django 5.1.3 on 2024-11-12 21:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['uuid'], name='client_clie_uuid_82e0b3_idx'), models.Index(fields=['created_at'], name='client_clie_created_aab6e4_idx'), models.Index(fields=['updated_at'], name='client_clie_updated_b97dd2_idx'), models.Index(fields=['name'], name='client_clie_name_5f3fd4_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClientEnvironment',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('environment', models.CharField(default='prod', max_length=128)),
                ('redirect_url', models.CharField(max_length=2048)),
                ('auth_token', models.CharField(max_length=256)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientWebhook',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('webhook_url', models.CharField(max_length=2048)),
                ('type', models.CharField(choices=[('auth', 'Auth'), ('subscription', 'Subscription')], max_length=32)),
                ('client_environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.clientenvironment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128)),
                ('website', models.CharField(max_length=2048)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['uuid'], name='client_clie_uuid_d3c673_idx'), models.Index(fields=['created_at'], name='client_clie_created_30de2f_idx'), models.Index(fields=['updated_at'], name='client_clie_updated_108e37_idx'), models.Index(fields=['name'], name='client_clie_name_16f367_idx'), models.Index(fields=['email'], name='client_clie_email_d3a06e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='clientenvironment',
            index=models.Index(fields=['uuid'], name='client_clie_uuid_c08d55_idx'),
        ),
        migrations.AddIndex(
            model_name='clientenvironment',
            index=models.Index(fields=['created_at'], name='client_clie_created_9b8c42_idx'),
        ),
        migrations.AddIndex(
            model_name='clientenvironment',
            index=models.Index(fields=['updated_at'], name='client_clie_updated_53f821_idx'),
        ),
        migrations.AddIndex(
            model_name='clientenvironment',
            index=models.Index(fields=['environment'], name='client_clie_environ_0b1e7f_idx'),
        ),
        migrations.AddIndex(
            model_name='clientenvironment',
            index=models.Index(fields=['is_active'], name='client_clie_is_acti_4a04c5_idx'),
        ),
        migrations.AddIndex(
            model_name='clientwebhook',
            index=models.Index(fields=['uuid'], name='client_clie_uuid_165640_idx'),
        ),
        migrations.AddIndex(
            model_name='clientwebhook',
            index=models.Index(fields=['created_at'], name='client_clie_created_fa7874_idx'),
        ),
        migrations.AddIndex(
            model_name='clientwebhook',
            index=models.Index(fields=['updated_at'], name='client_clie_updated_470785_idx'),
        ),
        migrations.AddIndex(
            model_name='clientwebhook',
            index=models.Index(fields=['name'], name='client_clie_name_27d599_idx'),
        ),
        migrations.AddIndex(
            model_name='clientwebhook',
            index=models.Index(fields=['webhook_url'], name='client_clie_webhook_5cfe29_idx'),
        ),
        migrations.AddIndex(
            model_name='clientwebhook',
            index=models.Index(fields=['type'], name='client_clie_type_5bd6e6_idx'),
        ),
    ]
