# Generated by Django 5.1.3 on 2024-11-13 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(help_text="Client's name (for admin purposes)", max_length=128),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='email',
            field=models.CharField(help_text='The email to reach the contact', max_length=128),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='name',
            field=models.CharField(help_text='How the contact should be addressed', max_length=128),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='website',
            field=models.CharField(help_text='The website for the contact', max_length=2048),
        ),
        migrations.AlterField(
            model_name='clientenvironment',
            name='auth_token',
            field=models.CharField(help_text='The server-to-server/secret auth token', max_length=256),
        ),
        migrations.AlterField(
            model_name='clientenvironment',
            name='environment',
            field=models.CharField(default='prod', help_text='The environment (e.g. dev, stage, prod)', max_length=128),
        ),
        migrations.AlterField(
            model_name='clientenvironment',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this environment active?'),
        ),
        migrations.AlterField(
            model_name='clientenvironment',
            name='redirect_url',
            field=models.CharField(help_text='The redirect url back to the client after login', max_length=2048),
        ),
        migrations.AlterField(
            model_name='clientwebhook',
            name='name',
            field=models.CharField(help_text='The name of the webhook (for admin purposes)', max_length=128),
        ),
        migrations.AlterField(
            model_name='clientwebhook',
            name='type',
            field=models.CharField(choices=[('auth', 'Auth'), ('subscription', 'Subscription')], help_text='What type of webhook is it?', max_length=32),
        ),
        migrations.AlterField(
            model_name='clientwebhook',
            name='webhook_url',
            field=models.CharField(help_text='The URL of the webhook', max_length=2048),
        ),
    ]
