# Generated by Django 5.1.3 on 2024-11-14 23:14
import logging

from django.conf import settings
from django.db import migrations
from django.urls import reverse


def up(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    client_model = apps.get_model('client', 'Client')
    client_environment_model = apps.get_model('client', 'ClientEnvironment')
    client_contact_model = apps.get_model('client', 'ClientContact')

    client = client_model.objects.create(name='Accounts Admin Panel')

    client_contact = client_contact_model.objects.create(
        name='Main', email=settings.ADMIN_CONTACT, website=settings.ADMIN_WEBSITE, client_id=client.uuid
    )

    client_environment = client_environment_model.objects.create(
        environment=settings.APP_ENV,
        redirect_url=reverse('admin:index'),
        auth_token=None,
        is_active=True,
        client_id=client.uuid,
    )

    logging.info(f'Finished creating admin client {client.uuid}!')


class Migration(migrations.Migration):
    dependencies = [
        ('client', '0003_alter_clientenvironment_auth_token'),
    ]

    operations = [
        migrations.RunPython(up),
    ]
