# Generated by Django 5.1.3 on 2024-11-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_data_create_admin_panel_client_20241114_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(help_text="Client's name (must be unique.)", max_length=128, unique=True),
        ),
    ]
