# Generated by Django 5.1.3 on 2024-11-27 22:19

import thunderbird_accounts.client.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('client', '0005_alter_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientenvironment',
            name='auth_token',
            field=models.CharField(
                default=thunderbird_accounts.client.models._generate_secret,
                help_text='The server-to-server/secret auth token',
                max_length=256,
                null=True,
                unique=True,
            ),
        ),
    ]
