# Generated by Django 5.1.3 on 2025-02-25 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_clientenvironment_allowed_hostnames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcontact',
            name='email',
            field=models.CharField(help_text='The email to reach the contact', max_length=128, unique=True),
        ),
    ]
