# Generated by Django 5.1.3 on 2025-02-25 22:49

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_alter_clientcontact_email_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='clientenvironment',
            constraint=models.UniqueConstraint(models.OrderBy(django.db.models.functions.text.Lower('environment'), descending=True), models.F('redirect_url'), name='unique_lower_environment_and_redirect_url'),
        ),
    ]
