# Generated by Django 5.1.3 on 2025-03-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('client', '0009_clientenvironment_unique_lower_environment_and_redirect_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientenvironment',
            name='is_public',
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text='Are non-users allowed to sign up? Otherwise an allow list is checked.',
            ),
        ),
    ]
