# Generated by Django 5.1.7 on 2025-04-03 18:18

import thunderbird_accounts.client.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('client', '0012_populate_clientwebhook_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientwebhook',
            name='secret',
            field=models.CharField(
                default=thunderbird_accounts.client.models._generate_secret,
                help_text='The server-to-server/secret webhook secret',
                max_length=256,
                null=False,
                unique=True,
            ),
        ),
    ]
