---
resources:

  domains:
    accounts: accounts.tb.pro

  tb:network:MultiCidrVpc:
    vpc:
      cidr_block: 10.10.0.0/16
      subnets:
        eu-central-1a:
          - 10.10.0.0/17
        eu-central-1b:
          - 10.10.128.0/17
      enable_internet_gateway: True
      egress_via_internet_gateway: True
      enable_dns_hostnames: True
      endpoint_interfaces:
        - ecr.api
        - ecr.dkr
        - logs
        - secretsmanager

  tb:network:SecurityGroupWithRules:
    accounts-lb:
      rules:
        ingress:
          - description: TLS traffic to the load balancer from the world
            cidr_blocks:
              - 0.0.0.0/0
            protocol: tcp
            from_port: 443
            to_port: 443
        egress:
          - description: Allow outbound traffic to anywhere
            protocol: tcp
            from_port: 0
            to_port: 65535
            cidr_blocks:
              - 0.0.0.0/0

    accounts-container:
      rules:
        ingress:
            # Set the source in code to the accounts-lb SGID
          - description: Allow traffic from the load balancer to the container
            protocol: tcp
            from_port: 8087
            to_port: 8087
        egress:
          - description: Allow traffic from the container out to the Internet
            cidr_blocks:
              - 0.0.0.0/0
            protocol: tcp
            from_port: 0
            to_port: 65535
      
    accounts-redis:
      rules:
        ingress:
          # Set the source in code to the accounts-container SGID
          - description: Allow traffic from the accounts application to the container
            protocol: tcp
            from_port: 6379
            to_port: 6379
        egress: []

  tb:secrets:PulumiSecretsManager:
    pulumi:
      secret_names:
        - database-host
        - database-name
        - database-password
        - database-user
        - fxa-allow-list
        - fxa-client-id
        - fxa-secret
        - login-code-secret
        - secret-key
        - fxa-encrypt-secret
        - sentry-dsn
        - paddle-token
        - paddle-price-id-lo
        - paddle-price-id-md
        - paddle-price-id-hi
        - redis-url
  
  tb:ec2:SshableInstance: {}
  # Fill out this template to build an SSH bastion
  # tb:ec2:SshableInstance:
  #   bastion:
  #     ssh_keypair_name: your-ec2-keypair
  #     source_cidrs:
  #       - your.ip.addr.ess/32

  tb:elasticache:ElastiCacheReplicaGroup:
    accounts:
      num_cache_clusters: 1
      automatic_failover_enabled: False
      transit_encryption_mode: required
      transit_encryption_enabled: True
      apply_immediately: True
      
  tb:fargate:FargateClusterWithLogging:
    accounts:
      assign_public_ip: True  # Necessary, or else it can't talk out through the IG
      desired_count: 1
      ecr_resources:
        - arn:aws:ecr:eu-central-1:768512802988:repository/thunderbird/accounts*
      health_check_grace_period_seconds: 30 # Time before the LB checks for health of a new backend
      internal: False # This needs to be open to receive auth callbacks
      services:
        accounts:
          listener_port: 443
          listener_proto: HTTPS
          listener_cert_arn: arn:aws:acm:eu-central-1:768512802988:certificate/901fd0a8-b113-4672-adf7-9793aae844fa
          container_port: 8087
          container_name: accounts
          # "name" field is arbitrary, but must be unique and no longer than 32 chars
          name: accounts-prod
          health_check:
            healthy_threshold: 2
            unhealthy_threshold: 5
            interval: 30
            path: /health
      task_definition:
        network_mode: awsvpc
        cpu: 512
        memory: 2048
        requires_compatibilities:
          - FARGATE
        container_definitions:
          accounts:
            image: 768512802988.dkr.ecr.eu-central-1.amazonaws.com/thunderbird/accounts:e1bced21eb1c4ee2f2f25f416fe03a21e3f5f802
            portMappings:
              - name: accounts
                containerPort: 8087
                hostPort: 8087
                protocol: tcp
                appProtocol: http
            linuxParameters:
              initProcessEnabled: True
            secrets:
              - name: DATABASE_HOST
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:accounts/prod/database-host-u5Ly46
              - name: DATABASE_NAME
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:accounts/prod/database-name-1LT9GX
              - name: DATABASE_PASSWORD
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:accounts/prod/database-password-YEuGDS
              - name: DATABASE_USER
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:accounts/prod/database-user-aLCuis
              - name: FXA_ALLOW_LIST
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:accounts/prod/fxa-allow-list-6iQipk
              - name: FXA_CLIENT_ID
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:accounts/prod/fxa-client-id-ggzLOI
              - name: FXA_SECRET
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:accounts/prod/fxa-secret-yPR6T4
              - name: LOGIN_CODE_SECRET
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:accounts/prod/login-code-secret-OSoact
              - name: SECRET_KEY
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:accounts/prod/secret-key-omYUWK
              - name: FXA_ENCRYPT_SECRET
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:accounts/prod/fxa-encrypt-secret-MXgdBx
              - name: SENTRY_DSN
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:accounts/prod/sentry-dsn-aEWFMV
              - name: PADDLE_TOKEN
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:accounts/prod/paddle-token-aNOfo6
              - name: PADDLE_PRICE_ID_LO
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:accounts/prod/paddle-price-id-lo-MhLJdH
              - name: PADDLE_PRICE_ID_MD
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:accounts/prod/paddle-price-id-md-HAbQbW
              - name: PADDLE_PRICE_ID_HI
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:accounts/prod/paddle-price-id-hi-0gHjja
              - name: REDIS_URL
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:accounts/prod/redis-url-Nq3x1a
            environment:
              - name: ADMIN_WEBSITE
                value: https://www.thunderbird.net
              - name: ADMIN_CONTACT
                value: dummy@example.org
              - name: ALLOWED_HOSTS
                # value: '*'
                value: '*:8087,accounts.tb.pro,10.*,10.*:8087'
              - name: APP_ENV
                value: stage
              - name: AUTH_SCHEME
                value: fxa
              - name: FXA_CALLBACK
                value: https://accounts.tb.pro/api/v1/auth/fxa/callback
              - name: FXA_OAUTH_SERVER_URL
                value: https://oauth.stage.mozaws.net/v1
              - name: FXA_OPEN_ID_CONFIG
                value: https://accounts.stage.mozaws.net/.well-known/openid-configuration
              - name: FXA_PROFILE_SERVER_URL
                value: https://profile.stage.mozaws.net/v1
              - name: PUBLIC_BASE_URL
                value: accounts.tb.pro
              - name: SUPPORT_CONTACT
                value: dummy@example.org
              - name: CSRF_SECURE
                value: 'True'
              - name: CSRF_HTTPONLY
                value: 'True'
              - name: CSRF_TRUSTED_ORIGINS
                value: 'https://accounts.tb.pro'
              - name: ALLOWED_EMAIL_DOMAINS
                value: 'thundermail.com'
              - name: IMAP_HOST
                value: 'mail.thundermail.com'
              - name: IMAP_PORT
                value: '993'
              - name: IMAP_TLS
                value: 'True'
              - name: SMTP_HOST
                value: 'mail.thundermail.com'
              - name: SMTP_PORT
                value: '465'
              - name: SMTP_TLS
                value: 'True'
              - name: JMAP_HOST
                value: 'mail.thundermail.com'
              - name: JMAP_PORT
                value: '443'
              - name: JMAP_TLS
                value: 'True'
              - name: PADDLE_ENV
                value: 'sandbox'
              - name: REDIS_INTERNAL_DB
                value: '0'
              - name: REDIS_CELERY_DB
                value: '5'
              - name: REDIS_CELERY_RESULTS_DB
                value: '6'
              - name: REDIS_SHARED_DB
                value: '10'

    accounts-celery:
      assign_public_ip: True  # Necessary, or else it can't talk out through the IG
      build_load_balancer: False  # This service has no network inputs and thus needs no LB
      desired_count: 1
      ecr_resources:
        - arn:aws:ecr:eu-central-1:768512802988:repository/thunderbird/accounts-celery-worker*
      internal: True
      services: { }
      task_definition:
        network_mode: awsvpc
        cpu: 512
        memory: 2048
        requires_compatibilities:
          - FARGATE
        container_definitions:
          accounts:
            image: 768512802988.dkr.ecr.eu-central-1.amazonaws.com/thunderbird/accounts-celery-worker:e1bced21eb1c4ee2f2f25f416fe03a21e3f5f802
            linuxParameters:
              initProcessEnabled: True
            secrets:
              - name: DATABASE_HOST
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:accounts/prod/database-host-u5Ly46
              - name: DATABASE_NAME
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:accounts/prod/database-name-1LT9GX
              - name: DATABASE_PASSWORD
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:accounts/prod/database-password-YEuGDS
              - name: DATABASE_USER
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:accounts/prod/database-user-aLCuis
              - name: FXA_ALLOW_LIST
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:accounts/prod/fxa-allow-list-6iQipk
              - name: FXA_CLIENT_ID
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:accounts/prod/fxa-client-id-ggzLOI
              - name: FXA_SECRET
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:accounts/prod/fxa-secret-yPR6T4
              - name: LOGIN_CODE_SECRET
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:accounts/prod/login-code-secret-OSoact
              - name: SECRET_KEY
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:accounts/prod/secret-key-omYUWK
              - name: FXA_ENCRYPT_SECRET
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:accounts/prod/fxa-encrypt-secret-MXgdBx
              - name: SENTRY_DSN
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:accounts/prod/sentry-dsn-aEWFMV
              - name: PADDLE_TOKEN
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:accounts/prod/paddle-token-aNOfo6
              - name: PADDLE_PRICE_ID_LO
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:accounts/prod/paddle-price-id-lo-MhLJdH
              - name: PADDLE_PRICE_ID_MD
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:accounts/prod/paddle-price-id-md-HAbQbW
              - name: PADDLE_PRICE_ID_HI
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:accounts/prod/paddle-price-id-hi-0gHjja
              - name: REDIS_URL
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:accounts/prod/redis-url-Nq3x1a
            environment:
              - name: ADMIN_WEBSITE
                value: https://www.thunderbird.net
              - name: ADMIN_CONTACT
                value: dummy@example.org
              - name: APP_ENV
                value: stage
              - name: AUTH_SCHEME
                value: fxa
              - name: FXA_CALLBACK
                value: https://accounts.tb.pro/api/v1/auth/fxa/callback
              - name: FXA_OAUTH_SERVER_URL
                value: https://oauth.mozaws.net/v1
              - name: FXA_OPEN_ID_CONFIG
                value: https://accounts.mozaws.net/.well-known/openid-configuration
              - name: FXA_PROFILE_SERVER_URL
                value: https://profile.mozaws.net/v1
              - name: PUBLIC_BASE_URL
                value: accounts.tb.pro
              - name: SUPPORT_CONTACT
                value: dummy@example.org
              - name: CSRF_SECURE
                value: 'True'
              - name: CSRF_HTTPONLY
                value: 'True'
              - name: CSRF_TRUSTED_ORIGINS
                value: 'https://accounts.tb.pro'
              - name: ALLOWED_EMAIL_DOMAINS
                value: 'thundermail.com'
              - name: IMAP_HOST
                value: 'mail.thundermail.com'
              - name: IMAP_PORT
                value: '993'
              - name: IMAP_TLS
                value: 'True'
              - name: SMTP_HOST
                value: 'mail.thundermail.com'
              - name: SMTP_PORT
                value: '465'
              - name: SMTP_TLS
                value: 'True'
              - name: JMAP_HOST
                value: 'mail.thundermail.com'
              - name: JMAP_PORT
                value: '443'
              - name: JMAP_TLS
                value: 'True'
              - name: PADDLE_ENV
                value: 'sandbox'
              - name: REDIS_INTERNAL_DB
                value: '0'
              - name: REDIS_CELERY_DB
                value: '5'
              - name: REDIS_CELERY_RESULTS_DB
                value: '6'
              - name: REDIS_SHARED_DB
                value: '10'
