# Generated by Django 5.1.3 on 2024-11-13 22:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.CharField(help_text='The avatar url from Mozilla Accounts', max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(help_text='The display name from Mozilla Accounts', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='fxa_id',
            field=models.CharField(help_text="Mozilla Account's UID field", max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_used_email',
            field=models.CharField(
                help_text='The email previously used to login to Mozilla Accounts', max_length=256, null=True
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='UTC', help_text="The user's timezone", max_length=128),
        ),
    ]
