# Generated by Django 5.1.3 on 2024-11-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authentication', '0003_user__fxa_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(
                choices=[('en', 'English'), ('de', 'German')],
                default='en',
                help_text='The language the UI and system emails will display in',
                max_length=16,
            ),
        ),
    ]
