# Generated by Django 5.2.2 on 2025-06-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_usersession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fxa_id',
        ),
        migrations.AddField(
            model_name='user',
            name='oidc_id',
            field=models.CharField(help_text="OIDC's UID field", max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_used_email',
            field=models.CharField(help_text='The email previously used to login', max_length=256, null=True),
        ),
    ]
