# Generated by Django 5.2.2 on 2025-07-04 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_user_fxa_id_user_oidc_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='_fxa_token',
        ),
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
