# Generated by Django 5.2.4 on 2025-09-18 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_remove_user__fxa_token_delete_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_test_account',
            field=models.BooleanField(default=False, help_text='Whether this account is used for testing.', verbose_name='Test Account'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.CharField(help_text='The avatar url', max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(help_text='The display name', max_length=256, null=True),
        ),
    ]
