# Generated by Django 5.2.4 on 2025-10-24 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_user_username'),
        ('subscription', '0009_remove_plan_mail_storage_gb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plan',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscription.plan'),
        ),
    ]
