# Generated by Django 5.2.4 on 2025-10-29 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_user_plan'),
        ('subscription', '0009_remove_plan_mail_storage_gb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscription.plan'),
        ),
    ]
