# Generated by Django 5.2.4 on 2025-11-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_user_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_awaiting_payment_verification',
            field=models.BooleanField(default=False, help_text=(
            "The user has paid and we're waiting on Paddle to verify the payment was successful."
            '<br>'
            '<b>Note:</b> Please do not override this unless authorized.'
        ),),
        ),
    ]
