# Generated by Django 5.2.9 on 2025-12-03 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_user_is_awaiting_payment_verification'),
        ('subscription', '0009_remove_plan_mail_storage_gb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscription.plan'),
        ),
    ]
