# Generated by Django 5.2.8 on 2025-11-26 17:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_user_is_awaiting_payment_verification'),
        ('subscription', '0009_remove_plan_mail_storage_gb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscription.plan'),
        ),
        migrations.CreateModel(
            name='AllowListEntry',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('user', models.ForeignKey(blank=True, help_text='The user associated with this allow list entry, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['uuid'], name='authenticat_uuid_e78aab_idx'), models.Index(fields=['created_at'], name='authenticat_created_563f64_idx'), models.Index(fields=['updated_at'], name='authenticat_updated_1633ed_idx'), models.Index(fields=['email'], name='authenticat_email_860daa_idx')],
            },
        ),
    ]
