# Generated by Django 5.2.9 on 2025-12-10 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_alter_user_plan_allowlistentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allowlistentry',
            options={'verbose_name_plural': 'Allow list entries'},
        ),
    ]
