# Generated by Django 6.0.4 on 2026-05-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_user_recovery_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allowlistentry',
            options={'verbose_name_plural': 'Allow list entries'},
        ),
        migrations.AddField(
            model_name='allowlistentry',
            name='discount_id',
            field=models.CharField(blank=True, help_text='Optional Paddle discount id to apply during checkout.', max_length=256, null=True),
        ),
    ]
