# Generated by Django 6.0.6 on 2026-06-24 20:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_add_allowlist_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allowlistentry',
            options={'permissions': [('create_test_entry_via_api', 'Can create test entries via an api endpoint')], 'verbose_name_plural': 'Allow list entries'},
        ),
        migrations.AddField(
            model_name='allowlistentry',
            name='is_test_entry',
            field=models.BooleanField(default=False, help_text='Will this entry automatically create a test account.<br/><b>Note:</b> These entries are remove shortly after creation.', verbose_name='test entry'),
        ),
        migrations.AlterField(
            model_name='allowlistentry',
            name='discount_id',
            field=models.CharField(blank=True, help_text='Optional Paddle discount id to apply during checkout.', max_length=256, null=True, validators=[django.core.validators.RegexValidator(message='Enter a full Paddle discount id in the format dsc_ followed by 26 lowercase letters or numbers.', regex='^dsc_[a-z0-9]{26}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 3–150 characters.', max_length=150, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='username'),
        ),
        migrations.AddIndex(
            model_name='allowlistentry',
            index=models.Index(fields=['is_test_entry'], name='authenticat_is_test_4b8743_idx'),
        ),
    ]
