# Generated by Django 6.0.5 on 2026-06-09 00:50

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

def payment_pending_data_migration(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    User = apps.get_model('authentication', 'User')
    UserFlag = apps.get_model('authentication', 'UserFlag')
    for user in User.objects.filter(is_awaiting_payment_verification=True).all():
        UserFlag.objects.create(flag=UserFlag.Flags.PaymentPending, user=user)

def remove_user_flags(apps, schema_editor):
    UserFlag = apps.get_model('authentication', 'UserFlag')
    for user_flag in UserFlag.objects.all():
        user_flag.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_add_allowlist_discount'),
    ]


    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_awaiting_payment_verification',
            field=models.BooleanField(default=False, help_text='<b>Note:</b> This field has been replaced with UserFlag.payment_pending.'),
        ),
        migrations.CreateModel(
            name='UserFlag',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flag', models.CharField(choices=[('payment_pending', 'Payment Pending')], db_index=True, help_text='A given flag that will denote some application-specific behaviour.', max_length=32)),
                ('user', models.ForeignKey(help_text='The user associated with this flag.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['uuid'], name='authenticat_uuid_6add6b_idx'), models.Index(fields=['created_at'], name='authenticat_created_9f2f09_idx'), models.Index(fields=['updated_at'], name='authenticat_updated_eb533b_idx')],
            },
        ),
        migrations.RunPython(payment_pending_data_migration, remove_user_flags),
    ]
