# Generated by Django 6.0.6 on 2026-07-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_alter_allowlistentry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recovery_email_rejected_at',
            field=models.DateTimeField(
                blank=True,
                help_text='When an external email service permanently rejected the recovery email.',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='recovery_email_rejection_reason',
            field=models.CharField(
                blank=True,
                help_text='The reason an external email service permanently rejected the recovery email.',
                max_length=512,
                null=True,
            ),
        ),
    ]
