# Generated by Django 6.0.5 on 2026-06-09 16:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_add_user_flag'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userflag',
            name='authenticat_uuid_6add6b_idx',
        ),
        migrations.RemoveIndex(
            model_name='userflag',
            name='authenticat_created_9f2f09_idx',
        ),
        migrations.RemoveIndex(
            model_name='userflag',
            name='authenticat_updated_eb533b_idx',
        ),
        migrations.AddConstraint(
            model_name='userflag',
            constraint=models.UniqueConstraint(fields=('flag', 'user'), name='unique_flag'),
        ),
    ]
