# Generated by Django 6.0.8 on 2026-09-30 16:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authentication', '0017_user_recovery_email_rejection'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsernameBlockListEntry',
            fields=[
                (
                    'uuid',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'pattern',
                    models.CharField(
                        help_text='A full or partial string using wildcard `*`.<br><b>Example:</b> <code>thunderbird</code> to block <code>thunderbird@example.com</code>, or <code>thunderbird*</code> to block usernames like <code>thunderbird-admin@example.com</code>',
                        unique=True,
                        verbose_name='pattern',
                    ),
                ),
            ],
            options={
                'verbose_name_plural': 'Username block list entries',
                'abstract': False,
                'indexes': [
                    models.Index(fields=['uuid'], name='authenticat_uuid_11f328_idx'),
                    models.Index(fields=['created_at'], name='authenticat_created_81fb2a_idx'),
                    models.Index(fields=['updated_at'], name='authenticat_updated_6ecea2_idx'),
                    models.Index(fields=['pattern'], name='authenticat_pattern_e6bc1f_idx'),
                ],
            },
        ),
    ]
