# Generated by Django 5.2 on 2025-05-01 21:40

import django.db.models.deletion
import thunderbird_accounts.subscription.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paddle_product_id', thunderbird_accounts.subscription.models.PaddleId(db_index=True, default=None, max_length=256, null=True)),
                ('name', models.CharField(max_length=256)),
                ('mail_address_count', models.IntegerField(help_text='Amount of mail addresses a user can create.', null=True)),
                ('mail_domain_count', models.IntegerField(help_text='Amount of custom domains a user can have.', null=True)),
                ('mail_storage_gb', models.IntegerField(help_text='Amount of mail storage a user has access to (in GB).', null=True)),
                ('send_storage_gb', models.IntegerField(help_text='Amount of send storage a user has access to (in GB).', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paddle_id', thunderbird_accounts.subscription.models.PaddleId(db_index=True, default=None, max_length=256, null=True)),
                ('paddle_product_id', thunderbird_accounts.subscription.models.PaddleId(db_index=True, default=None, max_length=256, null=True)),
                ('name', models.CharField()),
                ('amount', models.CharField(help_text='Amount in lowest denomination for currency. e.g. 10 USD = 1000 (cents).')),
                ('currency', models.CharField(help_text='Three letter ISO 4217 currency code.')),
                ('price_type', models.CharField(choices=[('standard', 'Standard'), ('custom', 'Custom')], help_text='Is this a one-off price?')),
                ('billing_cycle_frequency', models.CharField(help_text='Amount of time in a billing cycle.')),
                ('billing_cycle_interval', models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('year', 'Year')], help_text='The unit of time in a billing cycle.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubscriptionItem',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(default=0)),
                ('paddle_price_id', thunderbird_accounts.subscription.models.PaddleId(db_index=True, default=None, max_length=256, null=True)),
                ('paddle_product_id', thunderbird_accounts.subscription.models.PaddleId(db_index=True, default=None, max_length=256, null=True)),
                ('paddle_subscription_id', thunderbird_accounts.subscription.models.PaddleId(db_index=True, default=None, max_length=256, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='customer',
        ),
        migrations.RemoveIndex(
            model_name='subscription',
            name='subscriptio_name_a325f2_idx',
        ),
        migrations.RemoveIndex(
            model_name='subscription',
            name='subscriptio_is_acti_b5f26e_idx',
        ),
        migrations.RemoveIndex(
            model_name='subscription',
            name='subscriptio_active__464b18_idx',
        ),
        migrations.RemoveIndex(
            model_name='subscription',
            name='subscriptio_inactiv_333b0e_idx',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='active_since',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='inactive_since',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='name',
        ),
        migrations.AddField(
            model_name='subscription',
            name='current_billing_period_ends_at',
            field=models.DateTimeField(help_text='date when the billing period ends.', null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='current_billing_period_starts_at',
            field=models.DateTimeField(help_text='date when the billing period starts.', null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='next_billed_at',
            field=models.DateTimeField(help_text='date when the subscription is next schedule to be billed.', null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='paddle_customer_id',
            field=thunderbird_accounts.subscription.models.PaddleId(db_index=True, default=None, help_text='The customer paddle id.', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('', 'None'), ('active', 'Active'), ('canceled', 'Canceled'), ('past_due', 'Past Due'), ('paused', 'Paused'), ('trialing', 'Trialing')], default='', help_text='The current subscription status.', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='transaction_origin',
            field=models.CharField(choices=[('api', 'Api'), ('subscription_charge', 'Subscription: Charge'), ('subscription_payment_method_change', 'Subscription: Payment method change'), ('subscription_recurring', 'Subscription: Recurring'), ('subscription_update', 'Subscription: Update'), ('web', 'Web')], help_text='where the transaction first start from.', null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='paddle_id',
            field=thunderbird_accounts.subscription.models.PaddleId(db_index=True, default=None, help_text='The subscription paddle id.', max_length=256, null=True),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status'], name='subscriptio_status_942cf7_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['uuid'], name='subscriptio_uuid_1206c3_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['created_at'], name='subscriptio_created_3f52d8_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['updated_at'], name='subscriptio_updated_f3c865_idx'),
        ),
        migrations.AddIndex(
            model_name='price',
            index=models.Index(fields=['uuid'], name='subscriptio_uuid_99c95f_idx'),
        ),
        migrations.AddIndex(
            model_name='price',
            index=models.Index(fields=['created_at'], name='subscriptio_created_d0c441_idx'),
        ),
        migrations.AddIndex(
            model_name='price',
            index=models.Index(fields=['updated_at'], name='subscriptio_updated_b85dce_idx'),
        ),
        migrations.AddField(
            model_name='subscriptionitem',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.price'),
        ),
        migrations.AddField(
            model_name='subscriptionitem',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.subscription'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.AddIndex(
            model_name='subscriptionitem',
            index=models.Index(fields=['uuid'], name='subscriptio_uuid_06507b_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionitem',
            index=models.Index(fields=['created_at'], name='subscriptio_created_5c83b6_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionitem',
            index=models.Index(fields=['updated_at'], name='subscriptio_updated_38b521_idx'),
        ),
    ]
