# Generated by Django 5.2.1 on 2025-05-21 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_transaction_remove_subscription_transaction_origin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionitem',
            name='price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subscription.price'),
        ),
    ]
