# Generated by Django 5.2.1 on 2025-05-27 17:46

import django.db.models.deletion
import thunderbird_accounts.subscription.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_alter_subscriptionitem_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paddle_id', thunderbird_accounts.subscription.models.PaddleId(db_index=True, default=None, max_length=256, null=True)),
                ('name', models.CharField()),
                ('description', models.TextField(null=True)),
                ('product_type', models.CharField(choices=[('standard', 'Standard'), ('custom', 'Custom')], help_text='Is this a catalog product (standard) or a custom product?')),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], help_text='Is this product active or archived (cannot be used.)')),
                ('webhook_updated_at', models.DateTimeField(help_text='date when this model was last updated by a paddle webhook.', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['webhook_updated_at'], name='subscriptio_webhook_089cb9_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['webhook_updated_at'], name='subscriptio_webhook_6d444e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['uuid'], name='subscriptio_uuid_a9a477_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='subscriptio_created_ab0d78_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['updated_at'], name='subscriptio_updated_f643f8_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='subscriptio_name_644070_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_type'], name='subscriptio_product_2712e0_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status'], name='subscriptio_status_d4732e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['webhook_updated_at'], name='subscriptio_webhook_08e87f_idx'),
        ),
        migrations.AddField(
            model_name='plan',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subscription.product'),
        ),
        migrations.AddField(
            model_name='price',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subscription.product'),
        ),
        migrations.AddField(
            model_name='subscriptionitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subscription.product'),
        ),
        migrations.AddIndex(
            model_name='price',
            index=models.Index(fields=['webhook_updated_at'], name='subscriptio_webhook_517db4_idx'),
        ),
    ]
