# Generated by Django 5.2.1 on 2025-05-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_product_subscription_subscriptio_webhook_089cb9_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='paddle_product_id',
        ),
        migrations.AddField(
            model_name='plan',
            name='visible_on_subscription_page',
            field=models.BooleanField(default=True, help_text='Is this plan visible on the subscription page?'),
        ),
    ]
