# Generated by Django 5.2.1 on 2025-05-29 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_remove_plan_paddle_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', help_text='Is this price active or archived (cannot be used.)'),
        ),
    ]
