# Generated by Django 5.2.1 on 2025-06-02 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0007_price_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='subscription.product'),
        ),
    ]
