# Generated by Django 5.2.4 on 2025-10-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0008_alter_plan_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='mail_storage_gb',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='send_storage_gb',
        ),
        migrations.AddField(
            model_name='plan',
            name='mail_storage_bytes',
            field=models.BigIntegerField(help_text='Amount of mail storage a user has access to (in bytes).', null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='send_storage_bytes',
            field=models.BigIntegerField(help_text='Amount of send storage a user has access to (in bytes).', null=True),
        ),
    ]
