# Generated by Django 5.2.9 on 2025-12-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0009_remove_plan_mail_storage_gb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='discount_amount',
            field=models.CharField(blank=True, help_text='Discount (if any) that is applied to the Subscription (after all items are totaled.)<br/>This field can be a flat amount or percentage. See `discount_type` for what this value represents.', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='discount_type',
            field=models.CharField(choices=[('', 'None'), ('percentage', 'Percentage'), ('flat', 'Flat'), ('flat_per_seat', 'Flat per seat')], default='', help_text='What the `discount_amount` field represents.', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionitem',
            name='price_override_amount',
            field=models.CharField(blank=True, help_text='Usually this is the localized amount the user pays.', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionitem',
            name='price_override_currency',
            field=models.CharField(blank=True, help_text='The currency code for the `price_override_amount`.', max_length=256, null=True),
        ),
    ]
