# Generated by Django 5.2.9 on 2025-12-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0010_subscription_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='subscriptionitem',
            index=models.Index(fields=['quantity'], name='subscriptio_quantit_2b7e7a_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionitem',
            index=models.Index(fields=['price_override_currency'], name='subscriptio_price_o_2a8a22_idx'),
        ),
    ]
