# Generated by Django 6.0.6 on 2026-07-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0011_subscriptionitem_subscriptio_quantit_2b7e7a_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='billing_cycle_frequency',
            field=models.CharField(blank=True, help_text='Amount of time in a billing cycle.', null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='billing_cycle_interval',
            field=models.CharField(blank=True, choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('year', 'Year')], help_text='The unit of time in a billing cycle.', null=True),
        ),
    ]
