---
name: deploy-production

concurrency:
  group: deploy-production
  cancel-in-progress: true

on:
  release:
    types:
      - published

permissions:
  contents: read

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    env:
      IS_CI_AUTOMATION: "yes"
    steps:
      - name: Check out the code
        if: contains(github.event.release.assets.*.name, 'ecr_tag.zip')
        uses: actions/checkout@v4

      - name: Download ECR tag artifact
        if: contains(github.event.release.assets.*.name, 'ecr_tag.zip')
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: ${{ github.event.release.id }}
          file: ecr_tag.zip

      - name: Configure AWS credentials
        if: contains(github.event.release.assets.*.name, 'ecr_tag.zip')
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Login to Amazon ECR
        id: login-ecr
        if: contains(github.event.release.assets.*.name, 'ecr_tag.zip')
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: "true"

      - name: Get version from pyproject.toml
        uses: SebRollen/toml-action@v1.2.0
        id: read-version
        with:
          file: 'pyproject.toml'
          field: 'project.version'

      - name: Retag image
        if: contains(github.event.release.assets.*.name, 'ecr_tag.zip')
        id: retag-image
        shell: bash
        run: |
          # Gather info
          unzip ecr_tag.zip  # Produces ecr_tag.txt
          source_tag=$(cat ecr_tag.txt)
          semver="${{ steps.read-version.outputs.value }}"
          target_tag="${{ steps.login-ecr.outputs.registry }}/${{ vars.PROJECT }}:$semver"

          # Output the target tag
          echo "target_tag=$target_tag" >> $GITHUB_OUTPUT

          # Retag the image and push it
          docker pull $source_tag
          docker tag $source_tag $target_tag
          docker push $target_tag

      - name: Set up Python 3.12
        if: contains(github.event.release.assets.*.name, 'ecr_tag.zip')
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Set up virtual environment
        if: contains(github.event.release.assets.*.name, 'ecr_tag.zip')
        shell: bash
        run: |
          python -m pip install virtualenv
          cd packages/send/pulumi
          virtualenv ./venv

      - name: Set up Pulumi environment
        if: contains(github.event.release.assets.*.name, 'ecr_tag.zip')
        id: pulumi-env
        shell: bash
        run: |
          cd packages/send/pulumi
          source ./venv/bin/activate
          curl -fsSL https://get.pulumi.com | sh
          pip install -Ur requirements.txt

      - name: Deploy version-tagged image to prod
        if: contains(github.event.release.assets.*.name, 'ecr_tag.zip')
        shell: bash
        run: |
          # Update the PATH to include the right version of Pulumi; this is non-trivial or impossible
          # to do with the GHA workflow "env" settings.
          export PATH="/home/runner/.pulumi/bin:$PATH"

          # Pull the versioned tag from the previous step
          target_tag="${{ steps.retag-image.outputs.target_tag }}"

          # Create a YAML config stump containing only the nested tree leading to the image tag update
          cd packages/send/pulumi
          cat << EOF > newimage.yaml
          resources:
            tb:fargate:FargateClusterWithLogging:
              backend:
                task_definition:
                  container_definitions:
                    backend:
                      image: "$target_tag"
          EOF

          # Use yq to merge the stump into the main config
          yq -i '. *= load("newimage.yaml")' config.prod.yaml
          export PULUMI_CONFIG_PASSPHRASE='${{ secrets.PULUMI_PASSPHRASE_PROD }}'

          # Set up the Pulumi environment and update the service
          source ./venv/bin/activate
          pulumi login s3://tb-send-suite-pulumi
          pulumi stack select prod
          TBPULUMI_DISABLE_PROTECTION=True \
            pulumi up -y --diff --target \
            'urn:pulumi:prod::send-suite::tb:fargate:FargateClusterWithLogging$aws:ecs/taskDefinition:TaskDefinition::send-suite-prod-fargate-taskdef' \
            --target-dependents

  deploy-frontend:
    runs-on: ubuntu-latest
    env:
      IS_CI_AUTOMATION: "yes"
    steps:
      - name: Download frontend source
        if: contains(github.event.release.assets.*.name, 'dist-web-prod.zip')
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: ${{ github.event.release.id }}
          file: dist-web-prod.zip

      - name: Configure AWS credentials
        if: contains(github.event.release.assets.*.name, 'dist-web-prod.zip')
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy to production
        if: contains(github.event.release.assets.*.name, 'dist-web-prod.zip')
        id: frontend-deploy
        shell: bash
        run: |
          unzip -d frontend-source dist-web-prod.zip
          cd frontend-source
          aws s3 cp . s3://tb-send-suite-prod-frontend/ --recursive

          # Invalidate the CDN
          aws cloudfront create-invalidation --distribution-id ${{ vars.PROD_CF_DISTRO_ID }} --paths "/*"

  deploy-xpi-prod:
    runs-on: ubuntu-latest
    env:
      IS_CI_AUTOMATION: "yes"
    steps:
      - name: Check out the code
        if: contains(github.event.release.assets.*.name, 'xpi-prod.zip')
        uses: actions/checkout@v4

      - name: Download XPI artifact
        id: xpi-download
        if: contains(github.event.release.assets.*.name, 'xpi-prod.zip')
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: ${{ github.event.release.id }}
          file: xpi-prod.zip

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Deploy to ATN
        if: contains(github.event.release.assets.*.name, 'xpi-prod.zip')
        id: xpi-deploy
        shell: bash
        env:
          ATN_API_KEY: "${{ secrets.ATN_API_KEY }}"
          ATN_API_SECRET: "${{ secrets.ATN_API_SECRET }}"
          BASE_URL: https://send.tb.pro/
        run: |
          # Initial setup of dependencies
          mv xpi-prod.zip packages/send
          npm install -g pnpm
          cd packages/send
          pnpm i --filter send-frontend
          unzip xpi-prod.zip
          rm -f xpi-prod.zip
          cd frontend
          pnpm deploy-xpi $(find .. -name 'send-suite-*.xpi')
